# Generated by Django 2.2.24 on 2024-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20240406_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст жалобы'),
        ),
    ]
