# Generated by Django 3.2 on 2024-04-09 12:27

from django.db import migrations
import phonenumbers


def save_right_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone_numbers = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_phone_numbers):
            flat.owner_pure_phone = parsed_phone_numbers
            flat.save()
        else:
            return None


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(save_right_phone_numbers, move_backward),
    ]
