# Generated by Django 3.2 on 2024-04-13 10:05

from django.db import migrations


def fill_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.iterator():
        Owner.objects.get_or_create(name=flat.owner_name, pure_phone=flat.owner_pure_phone, phonenumber=flat.owners_phonenumber)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.iterator():
        owner.name = None
        owner.pure_phone = None
        owner.phonenumber = None
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owner, move_backward),
    ]
