# Generated by Django 3.2 on 2024-04-13 19:00

from django.db import migrations


def add_flat_in_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners:
        flats = Flat.objects.filter(owner_name=owner.name)
        print(owner, flats)
        owner.flat.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20240413_1305'),
    ]

    operations = [
        migrations.RunPython(add_flat_in_owner)
    ]
